services:
  knn_api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: knn_api
    ports:
      - "8001:8001"
    volumes:
      - /mnt/c/Users/User/Desktop/MyMLOps/data:/app/data
    networks:
      - rakuten_network

networks:
  rakuten_network:
    external: true
