services:
  fastapi:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
    container_name: fastapi
    ports:
      - "8001:8001"
    restart: always
    networks:
      - rakuten_network

networks:
  rakuten_network:
    external: true
