{
 "title": "API Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total{status_code!=\"200\"}[1m])) / (sum(rate(api_requests_total[1m])))\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95, \n  sum by (le) (\n    rate(api_request_duration_seconds_bucket[1m])\n    )\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}