{
 "title": "Infrastructure Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disk Usuage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 *\n(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} \n     / node_filesystem_size_bytes{mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usuage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 *\n(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usuage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 - avg by (instance) (\n  rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}