x-airflow-common: &airflow-common
  # build: .
  image: apache/airflow:2.8.1
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_URI}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
    AIRFLOW__WEBSERVER__BASE_URL: ${AIRFLOW__WEBSERVER__BASE_URL}
    AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: ${AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX}
    AIRFLOW__WEBSERVER__WORKERS: ${AIRFLOW__WEBSERVER__WORKERS}
    AIRFLOW__WEBSERVER__WORKER_CLASS: ${AIRFLOW__WEBSERVER__WORKER_CLASS}
    AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: ${AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT}

    _PIP_ADDITIONAL_REQUIREMENTS: ${AIRFLOW_ADDITIONAL_PACKAGES}

    # DB_NAME: ${DB_NAME}
    # COLLECTION_NAME: ${COLLECTION_NAME}
    # MONGO_URI: ${MONGO_URI}
  env_file:
    - .env #.docker
    # ✅ Variante B (explizit, kontrolliert)
    # docker compose --env-file .env.docker up airflow-init
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ../src:/opt/airflow/src
    - ../scripts:/opt/airflow/scripts
    - ../data:/opt/airflow/data

  user: "${AIRFLOW_UID:-1000}:0"
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  airflow-init:
    <<: *airflow-common
    # image: apache/airflow:2.8.1
    container_name: airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_URI}
      # _AIRFLOW_WWW_USER_CREATE: "true"
      # _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_USERNAME}
      # _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_PASSWORD}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username ${AIRFLOW_USERNAME} --password ${AIRFLOW_PASSWORD} --firstname Admin --lastname User --role Admin --email admin@example.com"
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    container_name: airflow-webserver
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow-scheduler
    depends_on:
      - airflow-init
    restart: always

volumes:
  postgres-db-volume:

networks:
  default:
    driver: bridge
    name: rakuten_network

