x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.worker
  environment: &airflow-common-env
    DB_NAME: ${DB_NAME}
    COLLECTION_NAME: ${COLLECTION_NAME}
    MONGO_URI: ${MONGO_URI}
    LOCAL_ROOT: /opt/airflow
    LOCAL_DATA: /opt/airflow/data
    LOCAL_VENV: /opt/airflow/venv

    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_URI}
    AIRFLOW__CELERY__RESULT_BACKEND: ${AIRFLOW_RESULT_BACKEND}
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.basic_auth"

  volumes:
    - /mnt/c/Users/User/Desktop/Final_Test/airflow/dags:/opt/airflow/dags
    - /mnt/c/Users/User/Desktop/Final_Test/airflow/logs:/opt/airflow/logs
    - /mnt/c/Users/User/Desktop/Final_Test/airflow/plugins:/opt/airflow/plugins
    - /mnt/c/Users/User/Desktop/Final_Test/src:/opt/airflow/src
    - /mnt/c/Users/User/Desktop/Final_Test/src/utils:/opt/airflow/src/utils
    - /mnt/c/Users/User/Desktop/Final_Test/scripts:/opt/airflow/scripts
    - /mnt/c/Users/User/Desktop/Final_Test/data:/opt/airflow/data
  user: "0:0"
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy


services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    networks:
      - rakuten_network
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    restart: always

  redis:
    image: redis:latest
    container_name: airflow-redis
    networks:
      - rakuten_network
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    container_name: airflow-webserver
    networks:
      - rakuten_network
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow-scheduler
    networks:
      - rakuten_network
    healthcheck:
      test: [ "CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"' ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    container_name: airflow-worker
    networks:
      - rakuten_network
    volumes:
      - /mnt/c/Users/User/Desktop/Final_Test/airflow/dags:/opt/airflow/dags
      - /mnt/c/Users/User/Desktop/Final_Test/airflow/logs:/opt/airflow/logs
      - /mnt/c/Users/User/Desktop/Final_Test/airflow/plugins:/opt/airflow/plugins
      - /mnt/c/Users/User/Desktop/Final_Test/src:/opt/airflow/src
      - /mnt/c/Users/User/Desktop/Final_Test/src/utils:/opt/airflow/src/utils
      - /mnt/c/Users/User/Desktop/Final_Test/scripts:/opt/airflow/scripts
      - /mnt/c/Users/User/Desktop/Final_Test/data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c " airflow db "
    restart: "no"
    networks:
      - rakuten_network
    environment:
      <<: *airflow-common-env
      _AAIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow

  flower:
    <<: *airflow-common
    command: celery flower
    networks:
      - rakuten_network
    ports:
      - 5555:5555
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:5555/" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

volumes:
  postgres-db-volume:
  mongo-db-volume:

networks:
  rakuten_network:
    external: true
