FROM apache/airflow:2.8.1

# Damit wir Pakete installieren können
USER root

# Docker CLI installieren (neueste Version aus Docker repo)
RUN apt-get update && \
    apt-get install -y ca-certificates curl gnupg lsb-release && \
    mkdir -p /etc/apt/keyrings && \
    rm -f /etc/apt/keyrings/docker.gpg && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --batch --dearmor -o /etc/apt/keyrings/docker.gpg && \
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    rm -rf /var/lib/apt/lists/*

    
USER airflow

RUN pip install --no-cache-dir \
  torch==2.1.2+cpu \
  --index-url https://download.pytorch.org/whl/cpu && \
  pip install --no-cache-dir \
  transformers \
  pillow \
  numpy \
  pymongo \
  mlflow \
  apache-airflow-providers-docker \
  sentence-transformers 



